# Generated by Django 5.2.4 on 2025-08-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('mensaje', models.TextField(max_length=300)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
