# Generated by Django 5.2.4 on 2025-07-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('imagen_post', models.ImageField(blank=True, default='posts/img_post.png', null=True, upload_to='posts/')),
                ('genero', models.ForeignKey(default='S/N', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.genero')),
                ('plataforma', models.ForeignKey(default='S/N', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.plataforma')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
